apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: api
  name: tripinsights-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: tripinsights-ingress.ee4429d302c142b7bc97.ukwest.aksapp.io
    http:
      paths:
      - path: /api/poi
        pathType: Prefix
        backend:
          service: 
            name: tripinsights-poi-service
            port: 
              number: 80
      - path: /api/trips
        pathType: Prefix
        backend:
          service: 
            name: tripinsights-trips-service
            port: 
              number: 80
      - path: /api/user
        pathType: Prefix
        backend:
          service: 
            name: tripinsights-userprofile-service
            port: 
              number: 80
      - path: /api/user-java
        pathType: Prefix
        backend:
          service: 
            name: tripinsights-user-java-service
            port: 
              number: 80