apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kube-secrets
spec:
  provider: azure
  parameters:
    keyvaultName: "kube-secrets"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "b18100e9-ca68-46de-8ed5-fb144662c605" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: APIDEVPASSWORD       # In this example, 'ExampleSecret'
          objectAlias: API_DEV_PASSWORD
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: APIDEVUSER       # In this example, 'ExampleSecret'
          objectAlias: API_DEV_USER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: WEBDEVPASSWORD       # In this example, 'ExampleSecret'   
          objectAlias: WEB_DEV_PASSWORD
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: WEBDEVUSER       # In this example, 'ExampleSecret'   
          objectAlias: WEB_DEV_USER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLSERVER       # In this example, 'ExampleSecret'   
          objectAlias: SQL_SERVER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLDBNAME       # In this example, 'ExampleSecret'   
          objectAlias: SQL_DBNAME
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLPASSWORD       # In this example, 'ExampleSecret'   
          objectAlias: SQL_PASSWORD
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: SQLUSER       # In this example, 'ExampleSecret'   
          objectAlias: SQL_USER
          objectType: secret              # Object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
    tenantId: "4801d5ab-c8bc-4966-8131-1d50997cfa4d"               # the tenant ID containing the Azure Key Vault instance
  
